version: "3.8"
services:
  nodejs:
    build:
      context: .
    image: node-app-image
    ports:
      - "4000:3000"
    container_name: node-app
  mysql:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    container_name: mysql-app
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_task
    ports:
      - '3306:3306'
    expose:
      - 3306
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    container_name: phpmyadmin-app